version: '3.3'
services:
  # log:
  #   image: vmware/harbor-log:v1.5.2
  #   volumes:
  #     - log_volume:/var/log/docker/
  #     # - ./common/config/log/:/etc/logrotate.d/
  #   configs:
  #     - source: log_config
  #       target: /etc/logrotate.d/logrotate.conf
  #   networks:
  #     - harbor
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  registry:
    image: vmware/registry-photon:v2.6.2-v1.5.2
    configs:
      - source: registry_config
        target: /etc/registry/config.yml
        mode: 0755
      - source: registry_root
        target: /etc/registry/root.crt
        mode: 0755
    volumes:
      - registry_volume:/storage
      # - ./common/config/registry/:/etc/registry/
    networks:
      - harbor
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    # depends_on:
    #   - log
    # logging:
    #   driver: "syslog"
    #   options:  
    #     syslog-address: "tcp://log:10514"
    #     tag: "registry"
    deploy:
      mode: replicated
      replicas: 1
  mysql:
    image: vmware/harbor-db:v1.5.2
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - harbor
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    # env_file:
    #   - ./common/config/db/env
    # depends_on:
    #   - log
    # logging:
    #   driver: "syslog"
    #   options:  
    #     syslog-address: "tcp://log:10514"
    #     tag: "mysql"
  adminserver:
    image: vmware/harbor-adminserver:v1.5.2
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - EXT_ENDPOINT=http://harbor.moria.io
      - AUTH_MODE=db_auth
      - SELF_REGISTRATION=on
      - LDAP_URL=ldaps://ldap.mydomain.com
      - LDAP_SEARCH_DN=
      - LDAP_SEARCH_PWD=
      - LDAP_BASE_DN=ou=people,dc=mydomain,dc=com
      - LDAP_FILTER=
      - LDAP_UID=uid
      - LDAP_SCOPE=2
      - LDAP_TIMEOUT=5
      - LDAP_VERIFY_CERT=true
      - LDAP_GROUP_BASEDN=ou=group,dc=mydomain,dc=com
      - LDAP_GROUP_FILTER=objectclass=group
      - LDAP_GROUP_GID=cn
      - LDAP_GROUP_SCOPE=2
      - DATABASE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USR=root
      - MYSQL_PWD=root123
      - MYSQL_DATABASE=registry
      - REGISTRY_URL=http://registry:5000
      - TOKEN_SERVICE_URL=http://ui:8080/service/token
      - EMAIL_HOST=smtp.mydomain.com
      - EMAIL_PORT=25
      - EMAIL_USR=sample_admin@mydomain.com
      - EMAIL_PWD=abc
      - EMAIL_SSL=false
      - EMAIL_FROM=admin <sample_admin@mydomain.com>
      - EMAIL_IDENTITY=
      - EMAIL_INSECURE=false
      - HARBOR_ADMIN_PASSWORD=Harbor12345
      - PROJECT_CREATION_RESTRICTION=everyone
      - MAX_JOB_WORKERS=50
      - UI_SECRET=fhpQSxCVFDtu9PDx
      - JOBSERVICE_SECRET=bsN7TRD82G55UZWx
      - TOKEN_EXPIRATION=30
      - CFG_EXPIRATION=5
      - GODEBUG=netdns=cgo
      - ADMIRAL_URL=NA
      - WITH_NOTARY=False
      - WITH_CLAIR=False
      - CLAIR_DB_PASSWORD=password
      - CLAIR_DB_HOST=postgres
      - CLAIR_DB_PORT=5432
      - CLAIR_DB_USERNAME=postgres
      - CLAIR_DB=postgres
      - RESET=false
      - UAA_ENDPOINT=uaa.mydomain.org
      - UAA_CLIENTID=id
      - UAA_CLIENTSECRET=secret
      - UAA_VERIFY_CERT=true
      - UI_URL=http://ui:8080
      - JOBSERVICE_URL=http://jobservice:8080
      - CLAIR_URL=http://clair:6060
      - NOTARY_URL=http://notary-server:4443
      - REGISTRY_STORAGE_PROVIDER_NAME=filesystem
      - READ_ONLY=false
      - SKIP_RELOAD_ENV_PATTERN=$$^
      - RELOAD_KEY=
    # env_file:
    #   - ./common/config/adminserver/env
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - adminserver_config_volume:/etc/adminserver/config/
      # - adminserver_secretkey_volume:/etc/adminserver/key
      - adminserver_volume:/data/
    configs:
      - source: adminserver_key
        target: /etc/adminserver/key
        mode: 0755
    networks:
      - harbor
    # depends_on:
    #   - log
    # logging:
    #   driver: "syslog"
    #   options:  
    #     syslog-address: "tcp://log:10514"
    #     tag: "adminserver"
  ui:
    image: vmware/harbor-ui:v1.5.2
    environment:
      - LOG_LEVEL=info
      - CONFIG_PATH=/etc/ui/app.conf
      - UI_SECRET=zTcjeRMkB7N7T0VP
      - JOBSERVICE_SECRET=Z6OpX2B2pcGSREOi
      - GODEBUG=netdns=cgo
      - ADMINSERVER_URL=http://adminserver:8080
      - UAA_CA_ROOT=/etc/ui/certificates/uaa_ca.pem
      - _REDIS_URL=redis:6379
    # env_file:
    #   - ./common/config/ui/env
    deploy:
      mode: replicated
      replicas: 1
    configs:
      - source: ui_app_config
        target: /etc/ui/app.conf
        mode: 0755
      - source: ui_private_key_pem
        target: /etc/ui/private_key.pem
        mode: 0755
    volumes:
      # - ./common/config/ui/app.conf:/etc/ui/app.conf
      # - ./common/config/ui/private_key.pem:/etc/ui/private_key.pem
      # - ./common/config/ui/certificates/:/etc/ui/certificates/
      - ui_secretkey_volume:/etc/ui/key
      - ui_ca_volume:/etc/ui/ca/
      - ui_psc_volume:/etc/ui/token/
    networks:
      - harbor
    # depends_on:
    #   - log
    #   - adminserver
    #   - registry
    # logging:
    #   driver: "syslog"
    #   options:  
    #     syslog-address: "tcp://log:10514"
    #     tag: "ui"
  jobservice:
    image: vmware/harbor-jobservice:v1.5.2
    environment:
      - UI_SECRET=zTcjeRMkB7N7T0VP
      - JOBSERVICE_SECRET=Z6OpX2B2pcGSREOi
      - ADMINSERVER_URL=http://adminserver:8080
      - GODEBUG=netdns=cgo
    # env_file:
    #   - ./common/config/jobservice/env
    deploy:
      mode: replicated
      replicas: 1
    configs:
      - source: jobservice_config
        target: /etc/jobservice/config.yml
        mode: 0755
    volumes:
      - jobservice_volume:/var/log/jobs
      # - ./common/config/jobservice/config.yml:/etc/jobservice/config.yml
    networks:
      - harbor
    # depends_on:
    #   - redis
    #   - ui
    #   - adminserver
    # logging:
    #   driver: "syslog"
    #   options:  
    #     syslog-address: "tcp://log:10514"
    #     tag: "jobservice"
  redis:
    image: vmware/redis-photon:v1.5.2
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - redis_volume:/data
    networks:
      - harbor
    # depends_on:
    #   - log
    # logging:
    #   driver: "syslog"
    #   options:  
    #     syslog-address: "tcp://log:10514"
    #     tag: "redis"
  proxy:
    image: vmware/nginx-photon:v1.5.2
    deploy:
      mode: replicated
      replicas: 1
    configs:
      - source: proxy_config
        target: /etc/nginx/nginx.conf
    # volumes:
    #   - ./common/config/nginx:/etc/nginx
    networks:
      - harbor
    ports:
      - 8888:80
      - 443:443
      - 4443:4443
    # depends_on:
    #   - mysql
    #   - registry
    #   - ui
    #   - log
    # logging:
    #   driver: "syslog"
    #   options:  
    #     syslog-address: "tcp://log:10514"
    #     tag: "proxy"

configs: 
  adminserver_key: 
    file: /data/secretkey
  log_config:
    file: ./common/config/log/logrotate.conf
  registry_config: 
    file: ./common/config/registry/config.yml
  registry_root:
    file: ./common/config/registry/root.crt
  ui_app_config:
    file: ./common/config/ui/app.conf
  ui_private_key_pem:
    file: ./common/config/ui/private_key.pem
  jobservice_config:
    file: ./common/config/jobservice/config.yml
  proxy_config:
    file: ./common/config/nginx/nginx.conf

volumes:
  log_volume:
    driver: local
  registry_volume:
    driver: local
  mysql_volume: 
    driver: local
  adminserver_config_volume:
    driver: local
  # adminserver_secretkey_volume:
  #   driver: local
  adminserver_volume:
    driver: local
  ui_secretkey_volume:
    driver: local
  ui_ca_volume:
    driver: local
  ui_psc_volume:
    driver: local
  jobservice_volume:
    driver: local
  redis_volume:
    driver: local


networks:
  harbor:
    external: false

